# Generated by Django 5.2.4 on 2025-08-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Labores',
            fields=[
                ('id_labores', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_labora', models.CharField(max_length=255)),
                ('creado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'labores',
            },
        ),
    ]
