# Generated by Django 5.2.5 on 2025-08-29 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fincas', '0005_alter_lote_options_lote_unique_lote_por_finca'),
        ('trabajadores', '0002_alter_trabajador_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
                ('trabajador_externo', models.CharField(blank=True, help_text='Si la labor fue realizada por alguien no asignado a la finca.', max_length=200, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labores', to='fincas.finca')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labores', to='fincas.lote')),
                ('trabajador_interno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labores_internas', to='trabajadores.trabajador')),
            ],
        ),
    ]
