# Generated by Django 5.2.5 on 2025-08-29 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labor',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
