# Generated by Django 5.2.5 on 2025-08-29 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labores', '0002_labor_observaciones'),
        ('trabajadores', '0002_alter_trabajador_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleLabor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jornal', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ejecucion', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('um', models.CharField(blank=True, max_length=50, null=True)),
                ('labor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='labores.labor')),
                ('trabajador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trabajadores.trabajador')),
            ],
        ),
    ]
