# Generated by Django 5.2.5 on 2025-08-29 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labores', '0003_detallelabor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labor',
            name='trabajador_externo',
        ),
        migrations.RemoveField(
            model_name='labor',
            name='trabajador_interno',
        ),
        migrations.AddField(
            model_name='detallelabor',
            name='trabajador_externo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
