# Generated by Django 5.2.4 on 2025-08-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialJornales',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'historial_jornales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jornales',
            fields=[
                ('id_jornal', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('creado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jornales',
                'managed': False,
            },
        ),
    ]
