# Generated by Django 5.2.4 on 2025-08-12 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('labores', '0001_initial'),
        ('trabajadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jornales',
            fields=[
                ('id_jornal', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('creado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('id_labores', models.ForeignKey(blank=True, db_column='id_labores', null=True, on_delete=django.db.models.deletion.SET_NULL, to='labores.labores')),
                ('id_trabajador', models.ForeignKey(blank=True, db_column='id_trabajador', null=True, on_delete=django.db.models.deletion.SET_NULL, to='trabajadores.trabajadores')),
            ],
            options={
                'db_table': 'jornales',
            },
        ),
        migrations.CreateModel(
            name='HistorialJornales',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('id_jornal', models.ForeignKey(blank=True, db_column='id_jornal', null=True, on_delete=django.db.models.deletion.CASCADE, to='jornales.jornales')),
            ],
            options={
                'db_table': 'historial_jornales',
            },
        ),
    ]
