services:
  - type: web
    name: gestiagro-backend
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "cd Backend && gunicorn wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: Backend.settings
      - key: PYTHON_VERSION
        value: 3.10
