services:
  - type: web
    name: gestiagro-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "cd Backend && gunicorn Backend.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: Backend.settings
      - key: PYTHON_VERSION
        value: 3.10
