# Generated by Django 5.2.4 on 2025-08-12 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jornales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumos',
            fields=[
                ('id_insumo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_comercial', models.CharField(max_length=255)),
                ('ingrediente_activo', models.CharField(blank=True, max_length=255, null=True)),
                ('unidad_medida', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_insumo', models.CharField(blank=True, max_length=50, null=True)),
                ('creado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'insumos',
            },
        ),
        migrations.CreateModel(
            name='InsumosJornales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_utilizada', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('creado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('id_insumo', models.ForeignKey(db_column='id_insumo', on_delete=django.db.models.deletion.CASCADE, to='insumos.insumos')),
                ('id_jornal', models.ForeignKey(db_column='id_jornal', on_delete=django.db.models.deletion.CASCADE, to='jornales.jornales')),
            ],
            options={
                'db_table': 'insumos_jornales',
                'unique_together': {('id_insumo', 'id_jornal')},
            },
        ),
    ]
