# Generated by Django 5.2.5 on 2025-08-21 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('fincas', '0005_alter_lote_options_lote_unique_lote_por_finca'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='finca_asignada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mayordomos', to='fincas.finca'),
        ),
    ]
