# Generated by Django 5.2.4 on 2025-09-06 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_finca_asignada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('agronomo', 'Agrónomo'), ('mayordomo', 'Mayordomo')], default='mayordomo', max_length=20),
        ),
    ]
