# Generated by Django 5.2.5 on 2025-08-14 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_is_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('agronomo', 'Agrónomo'), ('mayordomo', 'Mayordomo')], default='agronomo', max_length=20),
        ),
    ]
