# Generated by Django 5.2.4 on 2025-08-12 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fincas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alertas',
            fields=[
                ('id_alerta', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_alerta', models.CharField(blank=True, max_length=255, null=True)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('fecha_envio', models.DateField(blank=True, null=True)),
                ('creado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('id_finca', models.ForeignKey(blank=True, db_column='id_finca', null=True, on_delete=django.db.models.deletion.SET_NULL, to='fincas.finca')),
                ('id_usuario_destinatario', models.ForeignKey(blank=True, db_column='id_usuario_destinatario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuarios')),
            ],
            options={
                'db_table': 'alertas',
            },
        ),
    ]
