# Generated by Django 5.2.4 on 2025-08-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajadores',
            fields=[
                ('id_trabajador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_trabajador', models.CharField(max_length=255)),
                ('cargo', models.CharField(max_length=255)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('creado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'trabajadores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrabajadoresFincas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'trabajadores_fincas',
                'managed': False,
            },
        ),
    ]
