# Generated by Django 5.2.4 on 2025-08-21 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fincas', '0005_alter_lote_options_lote_unique_lote_por_finca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('cargo', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('vacaciones', 'Vacaciones'), ('suspendido', 'Suspendido')], default='activo', max_length=20)),
                ('telefono', models.CharField(max_length=15)),
                ('finca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajadores', to='fincas.finca')),
            ],
        ),
    ]
