# Generated by Django 5.2.4 on 2025-08-12 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fincas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajadores',
            fields=[
                ('id_trabajador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_trabajador', models.CharField(max_length=255)),
                ('cargo', models.CharField(max_length=255)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('creado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'trabajadores',
            },
        ),
        migrations.CreateModel(
            name='TrabajadoresFincas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fincas_trabajadores_trab', to='fincas.finca')),
                ('id_trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajadores_fincas_trab', to='trabajadores.trabajadores')),
            ],
            options={
                'db_table': 'trabajadores_fincas',
                'unique_together': {('id_trabajador', 'id_finca')},
            },
        ),
    ]
