# Generated by Django 5.2.5 on 2025-08-26 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fincas', '0005_alter_lote_options_lote_unique_lote_por_finca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitoreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('observaciones', models.TextField(blank=True)),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoreos', to='fincas.finca')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoreos', to='fincas.lote')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroPlaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familia', models.CharField(max_length=100)),
                ('plaga', models.CharField(max_length=100)),
                ('promedio', models.FloatField()),
                ('monitoreo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='fitosanitario.monitoreo')),
            ],
        ),
    ]
