# Generated by Django 5.2.4 on 2025-08-25 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fincas', '0005_alter_lote_options_lote_unique_lote_por_finca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('Combustible', 'Combustible'), ('Fertilizante', 'Fertilizante'), ('Insecticida', 'Insecticida'), ('Fungicida', 'Fungicida'), ('Biologico', 'Biológico'), ('Otros', 'Otros')], max_length=30)),
                ('ingrediente', models.CharField(blank=True, max_length=150, null=True)),
                ('unidad', models.CharField(choices=[('Kg', 'Kg'), ('Lt', 'Lt')], default='Kg', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('Entrada', 'Entrada'), ('Salida', 'Salida')], max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad', models.CharField(default='Kg', max_length=5)),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='fincas.finca')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='fincas.lote')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='bodega.producto')),
            ],
        ),
    ]
