# Generated by Django 5.2.4 on 2025-08-25 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0001_initial'),
        ('fincas', '0005_alter_lote_options_lote_unique_lote_por_finca'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockFinca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='fincas.finca')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='bodega.producto')),
            ],
            options={
                'unique_together': {('producto', 'finca')},
            },
        ),
    ]
