# Generated by Django 5.2.4 on 2025-08-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VariablesClimaticas',
            fields=[
                ('id_variable', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_clima', models.CharField(max_length=255)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('creado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'variables_climaticas',
                'managed': False,
            },
        ),
    ]
