# Generated by Django 5.2.4 on 2025-08-26 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fincas', '0005_alter_lote_options_lote_unique_lote_por_finca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad', models.CharField(default='Kg', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fincas.finca')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fincas.lote')),
            ],
        ),
    ]
