# Generated by Django 5.2.4 on 2025-08-21 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fincas', '0005_alter_lote_options_lote_unique_lote_por_finca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_equipo', models.CharField(max_length=50, unique=True)),
                ('maquina', models.CharField(max_length=100)),
                ('referencia', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('Óptimo', 'Óptimo'), ('Mantenimiento', 'Mantenimiento'), ('Averiado', 'Averiado')], default='Óptimo', max_length=20)),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fincas.finca')),
            ],
        ),
    ]
