# Generated by Django 5.2.4 on 2025-08-22 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo')], max_length=50)),
                ('descripcion', models.TextField()),
                ('realizado_por', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='equipos.maquina')),
            ],
        ),
    ]
