# Generated by Django 5.2.4 on 2025-08-22 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0002_mantenimiento'),
        ('fincas', '0005_alter_lote_options_lote_unique_lote_por_finca'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaborMaquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('labor', models.CharField(max_length=100)),
                ('horometro_inicio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('horometro_fin', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('finca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fincas.finca')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fincas.lote')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labores', to='equipos.maquina')),
            ],
        ),
    ]
