# Generated by Django 5.2.4 on 2025-08-04 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trabajadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finca',
            fields=[
                ('id_finca', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_finca', models.CharField(max_length=255)),
                ('ubicacion_finca', models.CharField(max_length=255)),
                ('coordenadas_finca', models.CharField(max_length=255)),
                ('area_finca_has', models.FloatField(db_column='area_finca_has')),
                ('creado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'finca',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FincaEquipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField()),
                ('estado_equipo', models.CharField(blank=True, max_length=100, null=True)),
                ('creado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'finca_equipos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id_lote', models.AutoField(primary_key=True, serialize=False)),
                ('numero_lote', models.CharField(max_length=255)),
                ('coordenadas_lote', models.CharField(blank=True, max_length=255, null=True)),
                ('area_lote_has', models.FloatField(db_column='area_lote_has')),
                ('cultivolote', models.CharField(blank=True, max_length=255, null=True)),
                ('creado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lote',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrabajadoresFincas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fincas_trabajadores_fincas', to='fincas.finca')),
                ('id_trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajadores_fincas_fincas', to='trabajadores.trabajadores')),
            ],
        ),
    ]
