# Generated by Django 5.2.4 on 2025-08-12 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finca',
            fields=[
                ('id_finca', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_finca', models.CharField(max_length=255)),
                ('ubicacion_finca', models.CharField(max_length=255)),
                ('coordenadas_finca', models.CharField(max_length=255)),
                ('area_finca_has', models.FloatField(db_column='area_finca_has')),
                ('creado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'finca',
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id_lote', models.AutoField(primary_key=True, serialize=False)),
                ('numero_lote', models.CharField(max_length=255)),
                ('coordenadas_lote', models.CharField(blank=True, max_length=255, null=True)),
                ('area_lote_has', models.FloatField(db_column='area_lote_has')),
                ('cultivolote', models.CharField(blank=True, max_length=255, null=True)),
                ('creado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('id_finca', models.ForeignKey(blank=True, db_column='id_finca', null=True, on_delete=django.db.models.deletion.CASCADE, to='fincas.finca')),
            ],
            options={
                'db_table': 'lote',
            },
        ),
        migrations.CreateModel(
            name='FincaEquipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField()),
                ('estado_equipo', models.CharField(blank=True, max_length=100, null=True)),
                ('creado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('id_equipo', models.ForeignKey(db_column='id_equipo', on_delete=django.db.models.deletion.CASCADE, to='equipos.equipos')),
                ('id_finca', models.ForeignKey(db_column='id_finca', on_delete=django.db.models.deletion.CASCADE, to='fincas.finca')),
            ],
            options={
                'db_table': 'finca_equipos',
                'unique_together': {('id_finca', 'id_equipo')},
            },
        ),
    ]
