# Generated by Django 5.2.4 on 2025-08-20 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fincas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variedad', models.CharField(max_length=100)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arboles', to='fincas.lote')),
            ],
        ),
    ]
