# Generated by Django 5.2.4 on 2025-08-20 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fincas', '0002_arbol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='variedad',
        ),
    ]
