# Generated by Django 5.2.4 on 2025-08-20 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fincas', '0003_remove_lote_variedad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='finca',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='lotes',
                to='fincas.finca',
            ),
        ),
        migrations.AlterField(
            model_name='arbol',
            name='lote',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='arboles',
                to='fincas.lote',
            ),
        ),
    ]
