# Generated by Django 5.2.4 on 2025-08-21 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fincas', '0004_alter_finca_lote_fk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lote',
            options={'verbose_name': 'Lote', 'verbose_name_plural': 'Lotes'},
        ),
        migrations.AddConstraint(
            model_name='lote',
            constraint=models.UniqueConstraint(fields=('finca', 'lote'), name='unique_lote_por_finca'),
        ),
    ]
