# Generated by Django 5.2.4 on 2025-07-18 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='backups/')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
