# Generated by Django 5.2.4 on 2025-08-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='seguimiento',
            field=models.TextField(blank=True, null=True),
        ),
    ]
