# Generated by Django 5.2.4 on 2025-08-26 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fincas', '0005_alter_lote_options_lote_unique_lote_por_finca'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroCampo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('anotaciones', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='cuaderno_fotos/')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_campo', to='fincas.finca')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_campo', to='fincas.lote')),
            ],
            options={
                'verbose_name': 'Registro de Campo',
                'verbose_name_plural': 'Registros de Campo',
                'ordering': ['-fecha', '-creado'],
            },
        ),
    ]
