# Generated by Django 5.2.4 on 2025-08-29 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuaderno_campo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrocampo',
            options={'ordering': ['-fecha', '-fecha_creacion'], 'verbose_name': 'Registro de Campo', 'verbose_name_plural': 'Registros de Campo'},
        ),
        migrations.RenameField(
            model_name='registrocampo',
            old_name='creado',
            new_name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='registrocampo',
            name='actualizado',
        ),
        migrations.AddField(
            model_name='registrocampo',
            name='creado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL),
        ),
    ]
