# Generated by Django 5.2.5 on 2025-08-29 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fincas', '0005_alter_lote_options_lote_unique_lote_por_finca'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramacionLabor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.IntegerField()),
                ('labor', models.CharField(max_length=200)),
                ('jornales', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('Iniciada', 'Iniciada'), ('En Proceso', 'En Proceso'), ('Terminada', 'Terminada'), ('Cancelada', 'Cancelada')], default='Iniciada', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labores_programadas', to='fincas.finca')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labores_programadas', to='fincas.lote')),
            ],
        ),
    ]
