# Generated by Django 5.2.4 on 2025-08-22 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fincas', '0005_alter_lote_options_lote_unique_lote_por_finca'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariableClimatica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('precipitacion', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('temp_min', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('temp_max', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('humedad', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='climas', to='fincas.finca')),
            ],
            options={
                'ordering': ['-fecha'],
                'unique_together': {('finca', 'fecha')},
            },
        ),
    ]
